exports.getAll = require('./getAll')
exports.getById = require('./getById')
exports.getByWorkshopId = require('./getByWorkshopId')
exports.update = require('./update')
exports.delete = require('./delete')
