exports.getAll = require('./getAll')
exports.getById = require('./getById')
exports.getByWorkshopManagerId = require('./getByWorkshopManagerId')
exports.update = require('./update')
exports.delete = require('./delete')
