exports.getAll = require('./getAll')
exports.getById = require('./getById')
exports.getByWorkShopManagerId = require('./getByName')
exports.update = require('./update')
exports.delete = require('./delete')
